### ISSUE TITLE
無法顯示求職小幫手

### ISSUE THREAD

**Issue by Ayukawayen** [abalone0204/Clairvoyance#53]
Console log
```
extensions::uncaught_exception_handler:8 Error in response to storage.get: ReferenceError: update_packages is not defined
    at Object.callback (chrome-extension://mdneakdlnoidknagkamfeambdefhppbi/dist/content-bundle.js:26:2978)
    at n (chrome-extension://mdneakdlnoidknagkamfeambdefhppbi/dist/content-bundle.js:26:2849)
    at Object.callback (chrome-extension://mdneakdlnoidknagkamfeambdefhppbi/dist/content-bundle.js:63:7884)
    handler @ extensions::uncaught_exception_handler:8
```

**Comment by Ayukawayen** [comment]
OK了

**Comment by abalone0204** [comment]
已經 hotfix  XD
